"""cascade delete comments when post is deleted

Revision ID: 5c64f01d832b
Revises: 7c799d108d88
Create Date: 2025-06-03 22:13:31.305981

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "5c64f01d832b"
down_revision: Union[str, None] = "7c799d108d88"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("attachment_thread_id_fkey"), "attachment", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "attachment", "thread", ["thread_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "attachment", type_="foreignkey")
    op.create_foreign_key(
        op.f("attachment_thread_id_fkey"), "attachment", "thread", ["thread_id"], ["id"]
    )
    # ### end Alembic commands ###
