"""cascade delete vote

Revision ID: 5e0dd496b23e
Revises: 72669b26821b
Create Date: 2025-06-03 10:19:06.984513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5e0dd496b23e'
down_revision: Union[str, None] = '72669b26821b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('vote_thread_id_fkey'), 'vote', type_='foreignkey')
    op.drop_constraint(op.f('vote_comment_id_fkey'), 'vote', type_='foreignkey')
    op.create_foreign_key(None, 'vote', 'thread', ['thread_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'vote', 'comment', ['comment_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vote', type_='foreignkey')
    op.drop_constraint(None, 'vote', type_='foreignkey')
    op.create_foreign_key(op.f('vote_comment_id_fkey'), 'vote', 'comment', ['comment_id'], ['id'])
    op.create_foreign_key(op.f('vote_thread_id_fkey'), 'vote', 'thread', ['thread_id'], ['id'])
    # ### end Alembic commands ###
