"""cascade delete comments when post is deleted

Revision ID: 7c799d108d88
Revises: 041add29650b
Create Date: 2025-06-03 22:04:53.214449

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "7c799d108d88"
down_revision: Union[str, None] = "041add29650b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("comment_thread_id_fkey"), "comment", type_="foreignkey")
    op.create_foreign_key(
        None, "comment", "thread", ["thread_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "comment", type_="foreignkey")
    op.create_foreign_key(
        op.f("comment_thread_id_fkey"), "comment", "thread", ["thread_id"], ["id"]
    )
    # ### end Alembic commands ###
